-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE personal_information ADD COLUMN id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;
