-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE accounts ADD COLUMN default_voucher TEXT REFERENCES vouchers(voucher_address);
