-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE swap_pools DROP CONSTRAINT swap_pools_swap_pool_description_check RESTRICT;
-- ALTER TABLE vouchers DROP CONSTRAINT vouchers_voucher_description_check RESTRICT;
