services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - cic-graph-pg:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  migrate:
    image: ghcr.io/jackc/tern:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PG_DATABASE_URL=postgres://postgres:postgres@postgres:5432/cic_graph?sslmode=disable
    volumes:
      - ../migrations:/migrations
    working_dir: /migrations
    command: ["migrate"]

volumes:
  cic-graph-pg:
    driver: local
