-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP TABLE IF EXISTS services CASCADE;
-- DROP TABLE IF EXISTS services_ratings, services_images, till, service_accepted_payment CASCADE;
